name = "constellation"
version = "0.1.0"
gleam = ">= 1.18.0"

description = "Demand-driven event pipelines and backpressure for Gleam and OTP"
licences = ["Apache-2.0"]
repository = { type = "github", user = "otavioabreu27", repo = "constellation" }
internal_modules = [
  "constellation/core/*",
  "constellation/domains/buffer",
  "constellation/domains/dispatcher/*",
  "constellation/runtime/effect_router",
  "constellation/runtime/registry",
  "constellation/runtime/otp/client",
  "constellation/runtime/otp/lifecycle",
  "constellation/runtime/otp/model",
  "constellation/runtime/otp/outbound",
  "constellation/runtime/otp/participant_monitors",
  "constellation/runtime/otp/server",
  "constellation/runtime/otp/trace",
  "constellation/source/core",
]

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
gleam_otp = ">= 1.3.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
logging = ">= 1.5.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
